package com.haulmont.testtask.Pharmacy.Designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PatientDesign extends FormLayout {
    protected TextField tfForename;
    protected TextField tfPatronymic;
    protected TextField tfSurname;
    protected TextField tfPhone;
    protected Button btnAdd;
    protected Button btnCancel;

    public PatientDesign() {
        Design.read(this);
    }
}
